name: 📚 Documentation Issue
description: Report an issue with documentation
title: "[Docs]: "
labels: ["documentation", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for helping improve our documentation!

  - type: dropdown
    id: type
    attributes:
      label: Documentation Type
      description: What type of documentation needs improvement?
      options:
        - README
        - DocC / API Documentation
        - Code Examples
        - Migration Guide
        - Other
    validations:
      required: true

  - type: textarea
    id: issue
    attributes:
      label: Issue Description
      description: Describe what's wrong or missing in the documentation
      placeholder: The documentation for X is unclear because...
    validations:
      required: true

  - type: input
    id: location
    attributes:
      label: Location
      description: Where is this documentation located? (file path, URL, method name, etc.)
      placeholder: e.g., README.md line 42, or RAWGClient.fetchGames()

  - type: textarea
    id: suggestion
    attributes:
      label: Suggested Improvement
      description: How would you improve this documentation?
      placeholder: I suggest changing it to...

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context or examples
